### ISSUE TITLE
激活不了

### ISSUE THREAD

**Issue by j2rong4cn** [MaterialCleaner/Media-Provider-Manager#13]
MIUI12 安卓10 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ComponentName.<init>(ComponentName.java:131)
	at android.content.Intent.<init>(Intent.java:6537)
	at mb.b.u(Unknown Source:19)
	at me.gm.cleaner.plugin.xposed.XposedInit$a.beforeHookedMethod(Unknown Source:10)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7216)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6699)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6594)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by GuhDoy** [comment]
需要更多信息
